apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
  namespace: mtasks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
      - name: flower
        image: task-platform:dev
        imagePullPolicy: IfNotPresent

        command: ["python", "-m", "celery"]
        args:
          - "-A"
          - "app.celery_app"
          - "flower"
          - "--address=0.0.0.0"
          - "--port=5555"

        env:
          - name: FLOWER_PORT
            value: "5555"
          - name: FLOWER_NO_ENV
            value: "true"

          - name: CELERY_BROKER_URL
            value: amqp://guest:guest@rabbitmq:5672//

          - name: CELERY_RESULT_BACKEND
            value: redis://redis:6379/0

        ports:
          - containerPort: 5555

---
apiVersion: v1
kind: Service
metadata:
  name: flower
  namespace: mtasks
spec:
  selector:
    app: flower
  ports:
    - port: 5555
